### ISSUE TITLE
Võrgukettal oleva faili allkirjastamisel antakse randomiga viga (kord õnnestub, siis mitte)

### ISSUE THREAD

**Issue by sander85** [open-eid/libdigidocpp#1] opened 2015-03-20 12:43 UTC
Koodis: https://github.com/open-eid/libdigidocpp/blob/74c9ca6624ab25ea77abeff35ab5ac68dd5048eb/src/util/ZipSerialize.cpp#L71

Veateade rakendusest: ZipSerialize.cpp:71 Failed to create ZIP file '//saialill/home$/kasutaja/TestFail2015.bdoc'

**Comment by martinpaljak** [comment] 2015-03-25 08:37
(the official language for development project is English)

I don't see what could be fixed in the code for this. Assuming the name of the file is the same, issues with underlying network or environment are out of reach of this codebase.

What CAN be done is hiding the underlying technical error from the user and display an understandable message instead.

**Comment by martinpaljak** [comment] 2015-03-25 08:58
For reference, the internal tracking number is IB-3687

**Comment by jkimalane** [comment] 2015-05-04 07:48
The same error occurred right after updating id-card software to latest release.

**Comment by priitpavelson** [comment] 2015-05-27 07:12
We have same problem with latest 3.10.3.1575 program, it affects ~1000 workers in our environment. Our Desktop and My Documents are redirected to UNC path \\servername\home\username\desktop

Problem with saving is random (at the moment we don't know how to reproduce this). When saving fails to UNC path at the same time it's possible to save it to same location on mapped drive Y:\Desktop and after that it's not possible to save the container on unc path.

After computer restart it works some time and happens again later.

Error message is as follows: Ümbriku salvestamine ebaõnnestus ZipSerialize.cpp:71 Failed to create ZIP file '//salv3/home/priit/Desktop/dokument.bdoc'.

**Comment by martinpaljak** [comment] 2015-10-21 06:08
How about 3.11 version? We have been trying to reproduce the error and fail to reliably reproduce the issue. In fact, we have not been able to reproduce the issue even once. Could you please verify with latest release and id possible, provide step by step instructions on how to reproduce and also the client environment details (operating system versions etc)

**Comment by priitpavelson** [comment] 2015-10-21 07:16
We cannot reproduce the issue either on newer versions, problem is solved for us.

**Comment by martinpaljak** [comment] 2015-10-22 13:21
Okay. Weirdness, but seems to be gone now.

**Closed by martinpaljak** 2015-10-22 13:21 UTC
Labels: enhancement
